/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

// Project Name:  PC6 Flashing (Blinking the led project).


#include <stdint.h>
void delay(uint32_t iterations) {
    for (uint32_t i = 0; i < iterations; i++);
}
int main(void)
{
	 uint32_t *pRCC_AHB1ENRReg = (uint32_t*)0x40023830; // RCC_AHB1ENR, PORT C CONNECTED
    *pRCC_AHB1ENRReg |= (1 << 2); // GPIO ENABLE, setting bit 2 of AHB1ENR

     uint32_t *pPORTCMODEReg = (uint32_t*)0x40020800; // GPIOC MODER, PC6
    *pPORTCMODEReg &= ~(3 << 12); // Clear bits 13 and 12 (set to 00) for pin 6
    *pPORTCMODEReg |= (1 << 12);  // Set bit 12 to 1 (01) for pin 6

     uint32_t *pPortCOutReg = (uint32_t*)0x40020814; // GPIOC ODR (Output Data Register)

    while (1)
    {
        *pPortCOutReg |= (1 << 6); // PC6 = 1; turn LED off

        delay(1000000);
        *pPortCOutReg &= ~(1 << 6); // PC6 = 0; turn LED on
        for( uint32_t i = 0; i < 300; i++);
        delay(1000000);
    }
}
