// Project Name:  PC6 Flashing (Blinking the lead project).
// Author : MathiYuvarajan
// Date : 28-07-2023
// Session: Afternoon

/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */


#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
    uint32_t *clockreg = (uint32_t*)0x40023830;//RCC->AHB1ENR
    uint32_t *moderreg = (uint32_t*)0x40020800;//GPIOC->MODER
    uint32_t *odrreg = (uint32_t*)0x40020814; //GPIOC->ODR
    *clockreg |=(1<<2); //PortC Clock Enable
    *moderreg |=(1<<12);//PC6 as output
    *moderreg &=~(1<<13);//PC6 as output
    while(1)
    {
    	*odrreg &=~(1<<6); //PC6=0 Led On
    	for(uint32_t i=0;i<200000;i++);
    	*odrreg |= (1<<6); //PC6=1 Led Off
    	for(uint32_t i=0;i<200000;i++);
    }
    return 0;
}
